### ISSUE TITLE
Reestruturação do Projeto

### ISSUE THREAD

**Issue by fernandoslv** [prodest/organograma-web-app#10]
Reestruturação do Projeto

**Comment by fontourafernando** [comment]
Separação do WorkService como uma nova camada de Apresentação.
Utilização da camada de Apresentação por injeção de dependência.

**Comment by fontourafernando** [comment]
Separação do WorkService como uma nova camada de Apresentação.
Utilização da camada de Apresentação por injeção de dependência.
